In [ ]:
import pandas as pd 
import os
import sqlalchemy as text
from sqlalchemy import create_engine

df = pd.read_csv("D:\\urban-environment-analytics\\data\\BandraMumbaiMPCB.csv")
df.head()
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76363 entries, 0 to 76362
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  76363 non-null  object
 1   PM2.5      24567 non-null  float64
 2   PM10       25976 non-null  float64
 3   NO2        21092 non-null  float64
 4   SO2        25085 non-null  float64
 5   CO         23468 non-null  float64
 6   Temp       25586 non-null  float64
 7   RH         25210 non-null  float64
dtypes: float64(7), object(1)
memory usage: 4.7+ MB

timestamp        0
PM2.5        51796
PM10         50387
NO2          55271
SO2          51278
CO           52895
Temp         50777
RH           51153
dtype: int64

In [5]:
columns_to_drop = [
    "Unnamed: 0",
    "To Date",
    "NO",
    "NOx",
    "Ozone",
    "Benzene",
    "Toluene",
    "WS",
    "WD",
    "SR",
    "BP",
    "VWS",
    "RF",
    "TOT-RF"
]
df = df.drop(columns=columns_to_drop, errors="ignore")
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76363 entries, 0 to 76362
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  76363 non-null  object
 1   PM2.5      24567 non-null  float64
 2   PM10       25976 non-null  float64
 3   NO2        21092 non-null  float64
 4   SO2        25085 non-null  float64
 5   CO         23468 non-null  float64
 6   Temp       25586 non-null  float64
 7   RH         25210 non-null  float64
dtypes: float64(7), object(1)
memory usage: 4.7+ MB

In [6]:
df = df.rename(columns={"From Date": "timestamp"})
df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76363 entries, 0 to 76362
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  76363 non-null  datetime64[ns]
 1   PM2.5      24567 non-null  float64
 2   PM10       25976 non-null  float64
 3   NO2        21092 non-null  float64
 4   SO2        25085 non-null  float64
 5   CO         23468 non-null  float64
 6   Temp       25586 non-null  float64
 7   RH         25210 non-null  float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 4.7 MB

In [7]:
ordered_columns = [
    "timestamp",
    "PM2.5",
    "PM10",
    "NO2",
    "SO2",
    "CO",
    "Temp",
    "RH"  
]

df = df[ordered_columns]

In [8]:
df.to_csv("D:\\urban-environment-analytics\\data\\BandraMumbaiMPCB.csv", index=False)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76363 entries, 0 to 76362
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  76363 non-null  datetime64[ns]
 1   PM2.5      24567 non-null  float64
 2   PM10       25976 non-null  float64
 3   NO2        21092 non-null  float64
 4   SO2        25085 non-null  float64
 5   CO         23468 non-null  float64
 6   Temp       25586 non-null  float64
 7   RH         25210 non-null  float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 4.7 MB

In [13]:
df.shape

(76363, 8)

In [14]:
df.columns

Index(['timestamp', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Temp', 'RH'], dtype='object')

In [15]:
df.head()

            timestamp  PM2.5   PM10   NO2    SO2    CO   Temp     RH
0 2021-01-01 00:00:00  35.99  54.30  0.93  16.15  2.01  25.50  81.70
1 2021-01-01 00:15:00  17.30  60.96  0.96  17.11  2.03  25.42  82.22
2 2021-01-01 00:30:00  10.66  57.51  0.92  15.24  2.05  25.00  85.10
3 2021-01-01 00:45:00   5.69  54.66  0.72  16.45  2.06  25.00  85.10
4 2021-01-01 01:00:00   9.84  53.59  0.93  15.58  2.07  25.00  85.10

In [16]:
df.describe()

,timestamp,PM2.5,PM10,NO2,SO2,CO,Temp,RH
count,76363,24567.000000,25976.000000,21092.000000,25085.000000,23468.000000,25586.000000,25210.000000
mean,2022-02-07 07:24:08.653144064,35.657979,94.886973,10.334039,28.848964,0.754519,36.790753,79.201654
min,2021-01-01 00:00:00,0.010000,4.450000,0.030000,0.010000,0.000000,0.010000,8.800000
25%,2021-07-18 20:37:30,27.160000,87.400000,7.800000,14.600000,0.000000,27.742500,69.770000
50%,2022-02-02 17:15:00,38.000000,104.300000,8.130000,24.240000,0.030000,30.300000,81.530000
75%,2022-08-20 13:52:30,38.000000,104.300000,9.960000,38.850000,1.710000,57.900000,91.235000
max,2023-12-02 23:45:00,369.600000,552.950000,482.490000,199.220000,27.050000,59.910000,99.900000
std,NaN,16.387766,26.515045,22.968742,17.290058,0.963562,14.163242,16.080579

In [18]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace(".", "", regex=False)
      .str.replace("-", "_")
)

df.columns.tolist()

['timestamp', 'pm25', 'pm10', 'no2', 'so2', 'co', 'temp', 'rh']

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76363 entries, 0 to 76362
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  76363 non-null  datetime64[ns]
 1   pm25       24567 non-null  float64
 2   pm10       25976 non-null  float64
 3   no2        21092 non-null  float64
 4   so2        25085 non-null  float64
 5   co         23468 non-null  float64
 6   temp       25586 non-null  float64
 7   rh         25210 non-null  float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 4.7 MB

In [22]:
df.isnull().sum()

timestamp        0
pm25         51796
pm10         50387
no2          55271
so2          51278
co           52895
temp         50777
rh           51153
dtype: int64

In [26]:
sensor_cols = ['pm25', 'pm10', 'no2', 'so2', 'co', 'temp', 'rh']

df = df.dropna(subset=sensor_cols, how='all')

for col in sensor_cols:
    df[col] = df[col].fillna(df[col].median()) # fills remaining missing values with median
    df = df[df[col] >= 0] # removes negative values
    
df.isnull().sum()

timestamp    0
pm25         0
pm10         0
no2          0
so2          0
co           0
temp         0
rh           0
dtype: int64

In [27]:
df.shape

(27146, 8)

In [ ]:
os.makedirs("data/processed", exist_ok=True)

df.to_csv("data/processed/cleaned_air_quality.csv", index=False) # cleaned dataset is saved for phase 2

In [ ]:
df = pd.read_csv(
    "data/processed/cleaned_air_quality.csv",
    parse_dates=["timestamp"]
) # reload cleaned csv

engine = create_engine(
    "postgresql+psycopg2://postgres:201204@localhost:5432/urban_env_analytics"
) # connected to postgres

df.to_sql(
    "air_quality",
    engine,
    if_exists="append",
    index=False
) # load data into the table

print("Data loaded successfully!")

Data loaded successfully!

In [4]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM air_quality"))
    print(result.fetchone())

(27146,)